# On clean le dataset de welcome to the jungle

In [1]:
import numpy as np
import pandas as pd
import re
import unidecode

In [2]:
df = pd.read_csv('/Users/saimanenawal/Documents/fichier_concaténé1.csv')

On renomme quelques colones pour pouvoir concatenner avec l autre data set

In [38]:
df.rename(columns={'job_title': 'intitule', 'education_level': 'etude_requise','contract': 'contrat', 'suitcase':'experience_requise', 'catégorie':'source','location':'departement', 'salary':'salaire_annuel'}, inplace=True)

On crée notre dictionnaire qui va nous servir pour convertir nos chiffre en str qui ont du sens

In [4]:
etude_num_2_str_dict  = {
    0 : "Aucune formation",
    1 : "4eme achevee",
    2 : "3eme achevee ou Brevet",
    3 : "CAP, BEP ou equivalent",
    4 : "Bac ou equivalent",
    5 : "Bac +2 ou equivalent",
    6 : "Bac +3 ou equivalent",
    7 : "Bac +4 ou equivalent",
    8 : "Bac +5 ou equivalent"
}

typeContrat_num_2_str_dict = {
    0 : 'CDI',
    1 : 'CDD',
    2 : 'MIS', 
    3 : 'DIN', 
    4 : 'CCE', 
    5 : 'LIB', 
    6 : 'FRA', 
    7 : 'SAI', 
    8 : 'REP', 
    9 : 'DDI', 
    10 : 'TTI'
}

tps_Pp_num_2_str_dict = {
    0 : "Temps partiel",
    1 : "Temps plein"
    }

Education_level

On regarde d'abord les valeurs de la colonne pour pouvoir convertir

In [5]:
df['etude_requise'].unique()

array([nan, ' Bac +5 / Master', ' Bac +4', ' Bac +2', ' Bac +3', ' Bac',
       ' Sans diplôme', ' > Bac +5 / Doctorat', ' Bac +1'], dtype=object)

In [10]:
convert_dict={' Bac +5 / Master': 8,  'Bac +4': 7, ' Bac +2': 5, ' Bac +3':6, ' Bac': 4,
       ' Sans diplôme': 0, ' > Bac +5 / Doctorat': 9, ' Bac +1': 4}

In [11]:
df['etude_requise']=df['etude_requise'].replace(convert_dict)

In [12]:
df

,company,intitule,date,contrat,location,salary,clock,remote,experience_requise,description,lien,etude_requise,catégorie
0,Tenzing Conseil,Manager Transformations durables H/F,"Friday 06 December 2024, 08:15 AM",CDI,Paris,Non spécifié,30 septembre 2024,Télétravail fréquent,> 7 ans,Tenzing accompagne les transitions durables da...,https://www.welcometothejungle.com/fr/companie...,NaN,Media
1,SAPER VEDERE,Social Media Analyst & Conseil en Influence / ...,"Tuesday 29 October 2024, 10:53 AM",Stage (6 à 12 mois),NaN,Non spécifié,05 janvier 2025,Télétravail fréquent,NaN,Qu’offrons-nous?Un stage (de 6 mois ou plus) à...,https://www.welcometothejungle.com/fr/companie...,NaN,Media
2,Eskimoz,Consultant Paid Media H/F - stage,"Tuesday 03 December 2024, 10:49 AM",Stage (6 mois),Boulogne-Billancourt,Non spécifié,NaN,Télétravail occasionnel,NaN,Gérer ton propre portefeuille client: start up...,https://www.welcometothejungle.com/fr/companie...,NaN,Media
3,Talan,Manager Média H/F,"Tuesday 24 December 2024, 09:01 AM",CDI,Paris,Non spécifié,NaN,Télétravail fréquent,> 2 ans,Company DescriptionTalan est un groupe interna...,https://www.welcometothejungle.com/fr/companie...,NaN,Media
4,datashake,Consultant Paid Media Senior - CDI - Paris,"Tuesday 24 December 2024, 08:37 AM",CDI,Paris,Non spécifié,31 juillet 2024,Télétravail occasionnel,> 2 ans,"En rejoignant datashake, tu bénéficieras d’une...",https://www.welcometothejungle.com/fr/companie...,8,Media
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19358,URGO,Chargé(e) de développement des ressources huma...,"Thursday 12 December 2024, 11:12 AM",CDI,Paris,Non spécifié,05 janvier 2025,Télétravail non autorisé,NaN,Missions :En tant que Chargé(e) de Projet RH a...,https://www.welcometothejungle.com/fr/companie...,8,ressources humaines
19359,bioMérieux,CDD 6 mois Assistant Ressources Humaines Génér...,"Thursday 12 December 2024, 10:20 AM",CDD / Temporaire (6 mois),Marcy-l'Étoile,Non spécifié,NaN,Télétravail non autorisé,> 3 ans,Rattaché au Responsable RH du site de Marcy l...,https://www.welcometothejungle.com/fr/companie...,6,ressources humaines
19360,City One,Gestionnaire des Ressources Humaines H/F,"Thursday 12 December 2024, 22:25 PM",CDI,Paris,Non spécifié,NaN,Télétravail non renseigné,NaN,Missions principales du service : Le GEMA (Gro...,https://www.welcometothejungle.com/fr/companie...,NaN,ressources humaines
19361,FutureBrand,CDI - Responsable Ressources Humaines Senior (...,"Thursday 12 December 2024, 15:49 PM",CDI,Neuilly-sur-Seine,Non spécifié,31 janvier 2025,Télétravail fréquent,> 10 ans,Nous recherchons un ou une Responsable Ressour...,https://www.welcometothejungle.com/fr/companie...,NaN,ressources humaines
19362,Hôtel Pullman Paris Centre-Bercy,CDD - CHARGÉ(E) DES RESSOURCES HUMAINES H/F,"Thursday 12 December 2024, 14:52 PM",CDD / Temporaire (5 à 6 mois),Paris,"2,9K à 3,1K € par mois",09 mars 2025,Télétravail occasionnel,NaN,Nous vous proposons le challenge suivant…Dans ...,https://www.welcometothejungle.com/fr/companie...,NaN,ressources humaines

Maintenant on passe à suitcase experience_requise

In [13]:
df['experience_requise'].unique()

array([' > 7 ans', nan, ' > 2 ans', ' > 3 ans', ' > 5 ans', ' < 6 mois',
       ' > 4 ans', ' > 1 an', ' > 6 mois', ' > 15 ans', ' > 10 ans'],
      dtype=object)

In [ ]:
def convert_exp(level):
    if pd.isna(level):
        return None
    elif ' > 7 ans' in level:
        return 84
    elif ' > 2 ans' in level:
        return 24
    elif ' > 3 ans' in level:
        return 36
    elif ' > 5 ans' in level:
        return 60
    elif ' > 4 ans' in level:
        return 48
    elif ' > 1 ans' in level:
        return 12
    elif ' > 6 mois' in level:
        return 6
    elif ' > 15 ans' in level:
        return 180
    elif ' > 10 ans' in level:
        return 120
    elif ' < 6 mois' in level:
        return 0
    else:
        return None

In [15]:
df['experience_requise']=df['experience_requise'].apply(convert_exp)

In [16]:
df

,company,intitule,date,contrat,location,salary,clock,remote,experience_requise,description,lien,etude_requise,catégorie
0,Tenzing Conseil,Manager Transformations durables H/F,"Friday 06 December 2024, 08:15 AM",CDI,Paris,Non spécifié,30 septembre 2024,Télétravail fréquent,84.0,Tenzing accompagne les transitions durables da...,https://www.welcometothejungle.com/fr/companie...,NaN,Media
1,SAPER VEDERE,Social Media Analyst & Conseil en Influence / ...,"Tuesday 29 October 2024, 10:53 AM",Stage (6 à 12 mois),NaN,Non spécifié,05 janvier 2025,Télétravail fréquent,NaN,Qu’offrons-nous?Un stage (de 6 mois ou plus) à...,https://www.welcometothejungle.com/fr/companie...,NaN,Media
2,Eskimoz,Consultant Paid Media H/F - stage,"Tuesday 03 December 2024, 10:49 AM",Stage (6 mois),Boulogne-Billancourt,Non spécifié,NaN,Télétravail occasionnel,NaN,Gérer ton propre portefeuille client: start up...,https://www.welcometothejungle.com/fr/companie...,NaN,Media
3,Talan,Manager Média H/F,"Tuesday 24 December 2024, 09:01 AM",CDI,Paris,Non spécifié,NaN,Télétravail fréquent,24.0,Company DescriptionTalan est un groupe interna...,https://www.welcometothejungle.com/fr/companie...,NaN,Media
4,datashake,Consultant Paid Media Senior - CDI - Paris,"Tuesday 24 December 2024, 08:37 AM",CDI,Paris,Non spécifié,31 juillet 2024,Télétravail occasionnel,24.0,"En rejoignant datashake, tu bénéficieras d’une...",https://www.welcometothejungle.com/fr/companie...,8,Media
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19358,URGO,Chargé(e) de développement des ressources huma...,"Thursday 12 December 2024, 11:12 AM",CDI,Paris,Non spécifié,05 janvier 2025,Télétravail non autorisé,NaN,Missions :En tant que Chargé(e) de Projet RH a...,https://www.welcometothejungle.com/fr/companie...,8,ressources humaines
19359,bioMérieux,CDD 6 mois Assistant Ressources Humaines Génér...,"Thursday 12 December 2024, 10:20 AM",CDD / Temporaire (6 mois),Marcy-l'Étoile,Non spécifié,NaN,Télétravail non autorisé,36.0,Rattaché au Responsable RH du site de Marcy l...,https://www.welcometothejungle.com/fr/companie...,6,ressources humaines
19360,City One,Gestionnaire des Ressources Humaines H/F,"Thursday 12 December 2024, 22:25 PM",CDI,Paris,Non spécifié,NaN,Télétravail non renseigné,NaN,Missions principales du service : Le GEMA (Gro...,https://www.welcometothejungle.com/fr/companie...,NaN,ressources humaines
19361,FutureBrand,CDI - Responsable Ressources Humaines Senior (...,"Thursday 12 December 2024, 15:49 PM",CDI,Neuilly-sur-Seine,Non spécifié,31 janvier 2025,Télétravail fréquent,120.0,Nous recherchons un ou une Responsable Ressour...,https://www.welcometothejungle.com/fr/companie...,NaN,ressources humaines
19362,Hôtel Pullman Paris Centre-Bercy,CDD - CHARGÉ(E) DES RESSOURCES HUMAINES H/F,"Thursday 12 December 2024, 14:52 PM",CDD / Temporaire (5 à 6 mois),Paris,"2,9K à 3,1K € par mois",09 mars 2025,Télétravail occasionnel,NaN,Nous vous proposons le challenge suivant…Dans ...,https://www.welcometothejungle.com/fr/companie...,NaN,ressources humaines

On passe au type de contrat

In [17]:
df['contrat'].unique()

array(['CDI', 'Stage (6 à 12 mois)', 'Stage (6 mois)',
       'Stage (5 à 6 mois)', 'Stage', 'CDD / Temporaire (7 à 12 mois)',
       'Alternance (12 à 24 mois)', 'Stage (4 à 6 mois)',
       'Stage (6 à 8 mois)', 'Freelance', 'Stage (2 à 6 mois)',
       'CDD / Temporaire (12 mois)', 'CDD / Temporaire',
       'Stage (3 à 6 mois)', 'CDD / Temporaire (11 mois)', 'Alternance',
       'CDD / Temporaire (3 mois)', 'CDD / Temporaire (1 à 6 mois)',
       'CDD / Temporaire (6 à 12 mois)', 'Alternance (12 mois)',
       'Stage (6 à 3 mois)', 'CDD / Temporaire (9 mois)',
       'CDD / Temporaire (10 mois)', 'CDD / Temporaire (6 mois)', 'VIE',
       'Stage (1 à 2 mois)', 'CDD / Temporaire (1 mois)',
       'Alternance (6 mois)', 'CDD / Temporaire (7 mois)',
       'CDD / Temporaire (5 à 6 mois)', 'Stage (4 mois)',
       'Alternance (16 à 18 mois)', 'CDD / Temporaire (2 mois)',
       'Stage (4 à 9 mois)', 'Stage (12 mois)', 'Stage (6 à 10 mois)',
       'CDD / Temporaire (36 mois)', 'Autres', 'Alternance (24 mois)',
       'CDD / Temporaire (7 à 8 mois)', 'CDD / Temporaire (24 mois)',
       'Stage (6 à 9 mois)', 'Stage (3 à 12 mois)', 'Stage (2 à 4 mois)',
       'Stage (1 à 8 mois)', 'Stage (4 à 8 mois)', 'Stage (5 à 12 mois)',
       'Stage (3 à 4 mois)', 'Stage (3 mois)', 'Stage (1 à 6 mois)',
       'Stage (5 à 7 mois)', nan, 'CDD / Temporaire (6 à 7 mois)'],
      dtype=object)

In [18]:
def fill_type_contrat(niveau):
    if pd.isna(niveau):
        return None
    
    elif 'CDI' in niveau  :
        return 0
    elif 'CDD' in niveau:
        return 1
    elif niveau == 'MIS':
        return 2
    elif niveau == 'DIN':
        return 3
    elif niveau == 'CCE':
        return 4
    elif niveau == 'LIB':
        return 5
    elif 'Freelance' in niveau:
        return 6
    elif 'Alternance' in niveau:
        return 7
    elif niveau == 'REP':
        return 8
    elif niveau == 'DDI':
        return 9
    elif niveau == 'TTI':
        return 10
    elif 'Stage' in niveau:
        return 11
    elif 'VIE' in niveau:
        return 12
    else:
        return None  #Si le type de contrat ne correspond pas

In [20]:
df['contrat']=df['contrat'].apply(fill_type_contrat)

In [21]:
df

,company,intitule,date,contrat,location,salary,clock,remote,experience_requise,description,lien,etude_requise,catégorie
0,Tenzing Conseil,Manager Transformations durables H/F,"Friday 06 December 2024, 08:15 AM",0.0,Paris,Non spécifié,30 septembre 2024,Télétravail fréquent,84.0,Tenzing accompagne les transitions durables da...,https://www.welcometothejungle.com/fr/companie...,NaN,Media
1,SAPER VEDERE,Social Media Analyst & Conseil en Influence / ...,"Tuesday 29 October 2024, 10:53 AM",11.0,NaN,Non spécifié,05 janvier 2025,Télétravail fréquent,NaN,Qu’offrons-nous?Un stage (de 6 mois ou plus) à...,https://www.welcometothejungle.com/fr/companie...,NaN,Media
2,Eskimoz,Consultant Paid Media H/F - stage,"Tuesday 03 December 2024, 10:49 AM",11.0,Boulogne-Billancourt,Non spécifié,NaN,Télétravail occasionnel,NaN,Gérer ton propre portefeuille client: start up...,https://www.welcometothejungle.com/fr/companie...,NaN,Media
3,Talan,Manager Média H/F,"Tuesday 24 December 2024, 09:01 AM",0.0,Paris,Non spécifié,NaN,Télétravail fréquent,24.0,Company DescriptionTalan est un groupe interna...,https://www.welcometothejungle.com/fr/companie...,NaN,Media
4,datashake,Consultant Paid Media Senior - CDI - Paris,"Tuesday 24 December 2024, 08:37 AM",0.0,Paris,Non spécifié,31 juillet 2024,Télétravail occasionnel,24.0,"En rejoignant datashake, tu bénéficieras d’une...",https://www.welcometothejungle.com/fr/companie...,8,Media
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19358,URGO,Chargé(e) de développement des ressources huma...,"Thursday 12 December 2024, 11:12 AM",0.0,Paris,Non spécifié,05 janvier 2025,Télétravail non autorisé,NaN,Missions :En tant que Chargé(e) de Projet RH a...,https://www.welcometothejungle.com/fr/companie...,8,ressources humaines
19359,bioMérieux,CDD 6 mois Assistant Ressources Humaines Génér...,"Thursday 12 December 2024, 10:20 AM",1.0,Marcy-l'Étoile,Non spécifié,NaN,Télétravail non autorisé,36.0,Rattaché au Responsable RH du site de Marcy l...,https://www.welcometothejungle.com/fr/companie...,6,ressources humaines
19360,City One,Gestionnaire des Ressources Humaines H/F,"Thursday 12 December 2024, 22:25 PM",0.0,Paris,Non spécifié,NaN,Télétravail non renseigné,NaN,Missions principales du service : Le GEMA (Gro...,https://www.welcometothejungle.com/fr/companie...,NaN,ressources humaines
19361,FutureBrand,CDI - Responsable Ressources Humaines Senior (...,"Thursday 12 December 2024, 15:49 PM",0.0,Neuilly-sur-Seine,Non spécifié,31 janvier 2025,Télétravail fréquent,120.0,Nous recherchons un ou une Responsable Ressour...,https://www.welcometothejungle.com/fr/companie...,NaN,ressources humaines
19362,Hôtel Pullman Paris Centre-Bercy,CDD - CHARGÉ(E) DES RESSOURCES HUMAINES H/F,"Thursday 12 December 2024, 14:52 PM",1.0,Paris,"2,9K à 3,1K € par mois",09 mars 2025,Télétravail occasionnel,NaN,Nous vous proposons le challenge suivant…Dans ...,https://www.welcometothejungle.com/fr/companie...,NaN,ressources humaines

Pour la source

In [25]:
df['source'].unique()

array(['Media', 'communication marketing', 'Education', 'Juridique',
       'Informatique technologie', 'conseil stratégie', 'finance',
       'Comptabilité', 'Transport', 'Hotellerie', 'graphisme',
       'Immobilier', 'Data', 'e-commerce', 'Environnement', 'audit',
       'santé', 'Agriculture', 'commercial business developer sales',
       'Ingénierie', 'ressources humaines'], dtype=object)

In [26]:
dict_c={ 'communication marketing':'Marketing',
       'Informatique technologie': 'Informatique', 'conseil stratégie':'Conseil', 'finance':'Finance', 'graphisme':'Graphisme','e-commerce':'E-commerce', 'audit':'Audit',
       'santé':'Sante', 'commercial business developer sales':'Vente',
       'Ingénierie':'Ingenierie', 'ressources humaines':'Ressources_Humaines'}

In [27]:
df['source']=df['source'].replace(dict_c)

In [28]:
df

,company,intitule,date,contrat,location,salary,clock,remote,experience_requise,description,lien,etude_requise,source
0,Tenzing Conseil,Manager Transformations durables H/F,"Friday 06 December 2024, 08:15 AM",0.0,Paris,Non spécifié,30 septembre 2024,Télétravail fréquent,84.0,Tenzing accompagne les transitions durables da...,https://www.welcometothejungle.com/fr/companie...,NaN,Media
1,SAPER VEDERE,Social Media Analyst & Conseil en Influence / ...,"Tuesday 29 October 2024, 10:53 AM",11.0,NaN,Non spécifié,05 janvier 2025,Télétravail fréquent,NaN,Qu’offrons-nous?Un stage (de 6 mois ou plus) à...,https://www.welcometothejungle.com/fr/companie...,NaN,Media
2,Eskimoz,Consultant Paid Media H/F - stage,"Tuesday 03 December 2024, 10:49 AM",11.0,Boulogne-Billancourt,Non spécifié,NaN,Télétravail occasionnel,NaN,Gérer ton propre portefeuille client: start up...,https://www.welcometothejungle.com/fr/companie...,NaN,Media
3,Talan,Manager Média H/F,"Tuesday 24 December 2024, 09:01 AM",0.0,Paris,Non spécifié,NaN,Télétravail fréquent,24.0,Company DescriptionTalan est un groupe interna...,https://www.welcometothejungle.com/fr/companie...,NaN,Media
4,datashake,Consultant Paid Media Senior - CDI - Paris,"Tuesday 24 December 2024, 08:37 AM",0.0,Paris,Non spécifié,31 juillet 2024,Télétravail occasionnel,24.0,"En rejoignant datashake, tu bénéficieras d’une...",https://www.welcometothejungle.com/fr/companie...,8,Media
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19358,URGO,Chargé(e) de développement des ressources huma...,"Thursday 12 December 2024, 11:12 AM",0.0,Paris,Non spécifié,05 janvier 2025,Télétravail non autorisé,NaN,Missions :En tant que Chargé(e) de Projet RH a...,https://www.welcometothejungle.com/fr/companie...,8,Ressources_Humaines
19359,bioMérieux,CDD 6 mois Assistant Ressources Humaines Génér...,"Thursday 12 December 2024, 10:20 AM",1.0,Marcy-l'Étoile,Non spécifié,NaN,Télétravail non autorisé,36.0,Rattaché au Responsable RH du site de Marcy l...,https://www.welcometothejungle.com/fr/companie...,6,Ressources_Humaines
19360,City One,Gestionnaire des Ressources Humaines H/F,"Thursday 12 December 2024, 22:25 PM",0.0,Paris,Non spécifié,NaN,Télétravail non renseigné,NaN,Missions principales du service : Le GEMA (Gro...,https://www.welcometothejungle.com/fr/companie...,NaN,Ressources_Humaines
19361,FutureBrand,CDI - Responsable Ressources Humaines Senior (...,"Thursday 12 December 2024, 15:49 PM",0.0,Neuilly-sur-Seine,Non spécifié,31 janvier 2025,Télétravail fréquent,120.0,Nous recherchons un ou une Responsable Ressour...,https://www.welcometothejungle.com/fr/companie...,NaN,Ressources_Humaines
19362,Hôtel Pullman Paris Centre-Bercy,CDD - CHARGÉ(E) DES RESSOURCES HUMAINES H/F,"Thursday 12 December 2024, 14:52 PM",1.0,Paris,"2,9K à 3,1K € par mois",09 mars 2025,Télétravail occasionnel,NaN,Nous vous proposons le challenge suivant…Dans ...,https://www.welcometothejungle.com/fr/companie...,NaN,Ressources_Humaines

Pour la location/ région

In [32]:
dict_reg={
    'Ain': 1, 'Aisne': 2, 'Allier': 3, 'Alpes-de-Haute-Provence': 4, 'Hautes-Alpes': 5, 
    'Alpes-Maritimes': 6, 'Ardèche': 7, 'Ardennes': 8, 'Ariège': 9, 'Aube': 10, 'Aude': 11, 
    'Aveyron': 12, 'Bouches-du-Rhône': 13, 'Calvados': 14, 'Cantal': 15, 'Charente': 16, 
    'Charente-Maritime': 17, 'Cher': 18, 'Corrèze': 19, 'Corse': 20, 'Côte-d\'Or': 21, 
    'Côtes-d\'Armor': 22, 'Creuse': 23, 'Dordogne': 24, 'Doubs': 25, 'Drôme': 26, 'Eure': 27, 
    'Eure-et-Loir': 28, 'Finistère': 29, 'Gard': 30, 'Haute-Garonne': 31, 'Gers': 32, 
    'Gironde': 33, 'Hérault': 34, 'Ille-et-Vilaine': 35, 'Indre': 36, 'Indre-et-Loire': 37, 
    'Isère': 38, 'Jura': 39, 'Landes': 40, 'Loir-et-Cher': 41, 'Loire': 42, 'Haute-Loire': 43, 
    'Loire-Atlantique': 44, 'Loiret': 45, 'Lot': 46, 'Lot-et-Garonne': 47, 'Lozère': 48, 
    'Maine-et-Loire': 49, 'Manche': 50, 'Marne': 51, 'Haute-Marne': 52, 'Mayenne': 53, 
    'Meurthe-et-Moselle': 54, 'Meuse': 55, 'Morbihan': 56, 'Moselle': 57, 'Nièvre': 58, 
    'Nord': 59, 'Oise': 60, 'Orne': 61, 'Pas-de-Calais': 62, 'Puy-de-Dôme': 63, 
    'Pyrénées-Atlantiques': 64, 'Hautes-Pyrénées': 65, 'Pyrénées-Orientales': 66, 
    'Bas-Rhin': 67, 'Haut-Rhin': 68, 'Rhône': 69, 'Haute-Saône': 70, 'Saône-et-Loire': 71, 
    'Sarthe': 72, 'Savoie': 73, 'Haute-Savoie': 74, 'Paris': 75, 'Seine-Maritime': 76, 
    'Seine-et-Marne': 77, 'Yvelines': 78, 'Deux-Sèvres': 79, 'Somme': 80, 'Tarn': 81, 
    'Tarn-et-Garonne': 82, 'Var': 83, 'Vaucluse': 84, 'Vendée': 85, 'Vienne': 86, 
    'Haute-Vienne': 87, 'Vosges': 88, 'Yonne': 89, 'Territoire de Belfort': 90, 'Essonne': 91, 
    'Hauts-de-Seine': 92, 'Seine-Saint-Denis': 93, 'Val-de-Marne': 94, 'Val-d\'Oise': 95, 
    'Guadeloupe': 971, 'Martinique': 972, 'Guyane': 973, 'La Réunion': 974, 'Mayotte': 976
}

In [33]:
df['departement']=df['departement'].replace(dict_reg)

In [35]:
df['departement'].unique()

array([75, nan, 'Boulogne-Billancourt', 'Cesson-Sévigné', 'Gentilly',
       'Issy-les-Moulineaux', 'Courbevoie', 'Rueil-Malmaison', 'Lyon',
       'La Défense', 'Toulouse', 'Bordeaux', 'Neuilly-sur-Seine',
       'La Garenne-Colombes', 'Choisy-le-Roi', 'Clichy', 'Belfort',
       'Gennevilliers', 'La Hague', 'Lille', 'Marseille', 'Épinal',
       'Jouy-en-Josas', 'Montrouge', 'Marcoussis', 'La Côte-Saint-André',
       'Montpellier', 'Calais', "Saint-Cyr-l'École", 'Villeurbanne',
       'Fontcouverte', 'Sarreguemines', 'Doué-en-Anjou', 'Beauvais',
       'Nanterre', 'Villeneuve-la-Garenne', 'Émerainville', 'Signes',
       "Villeneuve-d'Ascq", 'Bron', 'Niort', 'Marly-le-Roi', 'Saint-Lô',
       'Le Havre', 'Noisy-le-Grand', 'Le Mans', 'Bastia', 'Balma',
       'Tours', 'Cannes', 'Roissy-en-France', 'Challans', 'Les Mureaux',
       'Carrières-sur-Seine', 'Cambrai', 'Arras',
       'Artigues-près-Bordeaux', 'Nantes', 'Montreuil',
       'La Ferté-Saint-Aubin', 'Chartres', 'Mulhouse', 'Saint-Vulbas',
       'Issoudun', 'Le Plessis-Robinson', 'Vincennes', 'Pau',
       'Schiltigheim', 'Saint-Grégoire', 'Mérignac',
       'Oullins-Pierre-Bénite', 'Versailles', 'Bezons', 'Argenteuil',
       'Toulon', 'Malakoff', 'Vélizy-Villacoublay', 'Le Bouscat',
       'Montauban', 'Le Haillan', 'Nice', 'Voglans', 'Puteaux',
       'Pierrelatte', 'Villepinte', "Les Hauts-d'Anjou",
       'Brive-la-Gaillarde', 'Bègles', 'Compans', 'Vitré',
       'Aix-en-Provence', 'Limonest', 'Châtillon', 'Montbartier',
       'Strasbourg', 'Metz', 'Tourcoing', 'Saint-Priest',
       'Saint-Ouen-sur-Seine', 'Suresnes', 'Arcachon', 'Colombes',
       'Cassis', 'Gouvieux', 'Brest', 'Ivry-sur-Seine',
       'Croissy-sur-Seine', 'Chevilly-Larue', 'Levallois-Perret',
       'Grenoble', 'Avignon', 'Élancourt', 'Nancy', 'Roubaix', 'Talence',
       'Cornas', 'Mâcon', 'Franconville', 'Saint-Péray', 'La Verpillière',
       'Jard-sur-Mer', "Saint-Ouen-l'Aumône", 'Gaillac',
       'Épinay-sur-Orge', "Verteuil-d'Agenais", 'Saint-Médard-en-Jalles',
       'Marcq-en-Baroeul', 'Maisons-Alfort', 'Creysse',
       'Évry-Courcouronnes', 'Massy', 'Saint-Malo', 'Carquefou',
       'Bois-Colombes', 'Fuveau', 'Les Ulis', 'Labège', 'Vert-le-Grand',
       'Plaisir', 'Pantin', 'Craponne', 'Poissy', 'Rennes',
       'Mont-Saint-Aignan', 'Aubervilliers', 'Sophia-Antipolis',
       'Saint-Herblain', 'Tremblay-en-France', 'Eu', 'Alès',
       'Colombelles', 'Meudon', 'Charenton-le-Pont', 'Saint-Denis',
       'Mondeville', 'Sannerville', 'Évry', 'Angers', 'Fougères',
       'Fontenay-sous-Bois', 'Créteil', "Marcy-l'Étoile", 'Limours',
       'Villers-lès-Nancy', 'Le Plessis-Pâté', 'Vernon', 'Englos',
       'Cholet', 'Entzheim', 'Saint-Cloud', 'Poitiers', 'Léguevin',
       'Dijon', 'Joinville-le-Pont', 'Orleans', 'Échirolles', 'Morangis',
       'Aulnay-sous-Bois', 'Meylan', 'Domérat', 'Montluçon', 'Rouen',
       'Chambery', 'Montereau-sur-le-Jard', 'Wissous', 'Saint-Aubin',
       'Le Kremlin-Bicêtre', 'Nogent-sur-Vernisson', 'Réau',
       'Bagnols-sur-Cèze', 'Verberie', 'Lognes',
       'Montbonnot-Saint-Martin', 'Rungis', 'Noisy-le-Sec', 'Reims',
       'Magny-les-Hameaux', 'Troyes', 'Chaumont', 'Charleville-Mézières',
       'Éragny', 'Sochaux', 'Limeil-Brévannes', 'Limas', 'La Ciotat',
       'Bidart', 'Tassin-la-Demi-Lune', 'Palaiseau', 'Saint-Mandé',
       'Biot', 'Noisiel', 'Sèvres', 'Bagnolet', 'Montigny-le-Bretonneux',
       'Le Subdray', 'Maxéville', 'Puyoô', 'Bassens', 'Bois-Guillaume',
       'Beaumont-le-Roger', 'Reux', 'Lardy', 'Villiers-Saint-Frédéric',
       'Puiseux-Pontoise', 'Guyancourt', 'Saint-Marcel', 'Méry-sur-Oise',
       'Chusclan', 'Saint-Maurice', 'Amiens', 'Verrières-en-Anjou',
       'Ajaccio', 'Cornillé', 'Champagnole', 'Laval', 'Lempdes',
       'Châteauroux', 'Gasville-Oisème', 'Chalon-sur-Saône',
       'Saint-Martin-Boulogne', 'Benfeld', 'Golbey', 'Venelles',
       'Seiches-sur-le-Loir', 'Arcueil', 'Le Loroux-Bottereau', 'Tarbes',
       'Parthenay', 'Chalons-en-Champagne', 'Manosque', 'Orvault',
       'Saint-Martin-de-la-Porte', "Saint-Vigor-d'Ymonville"],
      dtype=object)

In [36]:
ville_to_departement = {
    'Boulogne-Billancourt': 92, 'Cesson-Sévigné': 35, 'Gentilly': 94, 'Issy-les-Moulineaux': 92,
    'Courbevoie': 92, 'Rueil-Malmaison': 92, 'Lyon': 69, 'La Défense': 92, 'Toulouse': 31, 
    'Bordeaux': 33, 'Neuilly-sur-Seine': 92, 'La Garenne-Colombes': 92, 'Choisy-le-Roi': 94, 
    'Clichy': 92, 'Belfort': 90, 'Gennevilliers': 92, 'La Hague': 50, 'Lille': 59, 'Marseille': 13, 
    'Épinal': 88, 'Jouy-en-Josas': 78, 'Montrouge': 92, 'Marcoussis': 91, 'La Côte-Saint-André': 38, 
    'Montpellier': 34, 'Calais': 62, "Saint-Cyr-l'École": 78, 'Villeurbanne': 69, 'Fontcouverte': 17, 
    'Sarreguemines': 57, 'Doué-en-Anjou': 49, 'Beauvais': 60, 'Nanterre': 92, 'Villeneuve-la-Garenne': 92, 
    'Émerainville': 77, 'Signes': 83, "Villeneuve-d'Ascq": 59, 'Bron': 69, 'Niort': 79, 'Marly-le-Roi': 78, 
    'Saint-Lô': 50, 'Le Havre': 76, 'Noisy-le-Grand': 93, 'Le Mans': 72, 'Bastia': 20, 'Balma': 31, 
    'Tours': 37, 'Cannes': 6, 'Roissy-en-France': 95, 'Challans': 85, 'Les Mureaux': 78, 'Carrières-sur-Seine': 78, 
    'Cambrai': 59, 'Arras': 62, 'Artigues-près-Bordeaux': 33, 'Nantes': 44, 'Montreuil': 93, 
    'La Ferté-Saint-Aubin': 45, 'Chartres': 28, 'Mulhouse': 68, 'Saint-Vulbas': 1, 'Issoudun': 36, 
    'Le Plessis-Robinson': 92, 'Vincennes': 94, 'Pau': 64, 'Schiltigheim': 67, 'Saint-Grégoire': 35, 
    'Mérignac': 33, 'Oullins-Pierre-Bénite': 69, 'Versailles': 78, 'Bezons': 95, 'Argenteuil': 95, 
    'Toulon': 83, 'Malakoff': 92, 'Vélizy-Villacoublay': 78, 'Le Bouscat': 33, 'Montauban': 82, 
    'Le Haillan': 33, 'Nice': 6, 'Voglans': 73, 'Puteaux': 92, 'Pierrelatte': 26, 'Villepinte': 93, 
    "Les Hauts-d'Anjou": 49, 'Brive-la-Gaillarde': 19, 'Bègles': 33, 'Compans': 31, 'Vitré': 35, 
    'Aix-en-Provence': 13, 'Limonest': 69, 'Châtillon': 92, 'Montbartier': 82, 'Strasbourg': 67, 
    'Metz': 57, 'Tourcoing': 59, 'Saint-Priest': 69, 'Saint-Ouen-sur-Seine': 93, 'Suresnes': 92, 
    'Arcachon': 33, 'Colombes': 92, 'Cassis': 13, 'Gouvieux': 60, 'Brest': 29, 'Ivry-sur-Seine': 94, 
    'Croissy-sur-Seine': 78, 'Chevilly-Larue': 94, 'Levallois-Perret': 92, 'Grenoble': 38, 'Avignon': 84, 
    'Élancourt': 78, 'Nancy': 54, 'Roubaix': 59, 'Talence': 33, 'Cornas': 7, 'Mâcon': 71, 
    'Franconville': 95, 'Saint-Péray': 7, 'La Verpillière': 38, 'Jard-sur-Mer': 85, "Saint-Ouen-l'Aumône": 95, 
    'Gaillac': 81, 'Épinay-sur-Orge': 91, "Verteuil-d'Agenais": 47, 'Saint-Médard-en-Jalles': 33, 
    'Marcq-en-Baroeul': 59, 'Maisons-Alfort': 94, 'Creysse': 24, 'Évry-Courcouronnes': 91, 'Massy': 91, 
    'Saint-Malo': 35, 'Carquefou': 44, 'Bois-Colombes': 92, 'Fuveau': 13, 'Les Ulis': 91, 'Labège': 31, 
    'Vert-le-Grand': 91, 'Plaisir': 78, 'Pantin': 93, 'Craponne': 69, 'Poissy': 78, 'Rennes': 35, 
    'Mont-Saint-Aignan': 76, 'Aubervilliers': 93, 'Sophia-Antipolis': 6, 'Saint-Herblain': 44, 
    'Tremblay-en-France': 93, 'Eu': 76, 'Alès': 30, 'Colombelles': 14, 'Meudon': 92, 'Charenton-le-Pont': 94, 
    'Saint-Denis': 93, 'Mondeville': 14, 'Sannerville': 14, 'Évry': 91, 'Angers': 49, 'Fougères': 35, 
    'Fontenay-sous-Bois': 94, 'Créteil': 94, "Marcy-l'Étoile": 69, 'Limours': 91, 'Villers-lès-Nancy': 54, 
    'Le Plessis-Pâté': 91, 'Vernon': 27, 'Englos': 59, 'Cholet': 49, 'Entzheim': 67, 'Saint-Cloud': 92, 
    'Poitiers': 86, 'Léguevin': 31, 'Dijon': 21, 'Joinville-le-Pont': 94, 'Orleans': 45, 'Échirolles': 38, 
    'Morangis': 91, 'Aulnay-sous-Bois': 93, 'Meylan': 38, 'Domérat': 3, 'Montluçon': 3, 'Rouen': 76, 
    'Chambery': 73, 'Montereau-sur-le-Jard': 77, 'Wissous': 91, 'Saint-Aubin': 91, 
    'Le Kremlin-Bicêtre': 94, 'Nogent-sur-Vernisson': 45, 'Réau': 77, 'Bagnols-sur-Cèze': 30, 
    'Verberie': 60, 'Lognes': 77, 'Montbonnot-Saint-Martin': 38, 'Rungis': 94, 'Noisy-le-Sec': 93, 'Reims': 51, 
    'Magny-les-Hameaux': 78, 'Troyes': 10, 'Chaumont': 52, 'Charleville-Mézières': 8, 'Éragny': 95, 
    'Sochaux': 25, 'Limeil-Brévannes': 94, 'Limas': 69, 'La Ciotat': 13, 'Bidart': 64, 
    'Tassin-la-Demi-Lune': 69, 'Palaiseau': 91, 'Saint-Mandé': 94, 'Biot': 6, 'Noisiel': 77, 
    'Sèvres': 92, 'Bagnolet': 93, 'Montigny-le-Bretonneux': 78, 'Le Subdray': 18, 'Maxéville': 54, 
    'Puyoô': 64, 'Bassens': 33, 'Bois-Guillaume': 76, 'Beaumont-le-Roger': 27, 'Reux': 27, 
    'Lardy': 91, 'Villiers-Saint-Frédéric': 78, 'Puiseux-Pontoise': 95, 'Guyancourt': 78, 
    'Saint-Marcel': 27, 'Méry-sur-Oise': 95, 'Chusclan': 30, 'Saint-Maurice': 94, 'Amiens': 80, 
    'Verrières-en-Anjou': 49, 'Ajaccio': 20, 'Cornillé': 44, 'Champagnole': 39, 'Laval': 53, 
    'Lempdes': 63, 'Châteauroux': 36, 'Gasville-Oisème': 28, 'Chalon-sur-Saône': 71, 
    'Saint-Martin-Boulogne': 62, 'Benfeld': 67, 'Golbey': 88, 'Venelles': 13, 'Seiches-sur-le-Loir': 49, 
    'Arcueil': 94, 'Le Loroux-Bottereau': 44, 'Tarbes': 65, 'Parthenay': 79, 'Chalons-en-Champagne': 51, 
    'Manosque': 4, 'Orvault': 44, 'Saint-Martin-de-la-Porte': 73, "Saint-Vigor-d'Ymonville": 51
}

In [37]:
df['departement']=df['departement'].replace(ville_to_departement)
df

,company,intitule,date,contrat,departement,salary,clock,remote,experience_requise,description,lien,etude_requise,source
0,Tenzing Conseil,Manager Transformations durables H/F,"Friday 06 December 2024, 08:15 AM",0.0,75.0,Non spécifié,30 septembre 2024,Télétravail fréquent,84.0,Tenzing accompagne les transitions durables da...,https://www.welcometothejungle.com/fr/companie...,NaN,Media
1,SAPER VEDERE,Social Media Analyst & Conseil en Influence / ...,"Tuesday 29 October 2024, 10:53 AM",11.0,NaN,Non spécifié,05 janvier 2025,Télétravail fréquent,NaN,Qu’offrons-nous?Un stage (de 6 mois ou plus) à...,https://www.welcometothejungle.com/fr/companie...,NaN,Media
2,Eskimoz,Consultant Paid Media H/F - stage,"Tuesday 03 December 2024, 10:49 AM",11.0,92.0,Non spécifié,NaN,Télétravail occasionnel,NaN,Gérer ton propre portefeuille client: start up...,https://www.welcometothejungle.com/fr/companie...,NaN,Media
3,Talan,Manager Média H/F,"Tuesday 24 December 2024, 09:01 AM",0.0,75.0,Non spécifié,NaN,Télétravail fréquent,24.0,Company DescriptionTalan est un groupe interna...,https://www.welcometothejungle.com/fr/companie...,NaN,Media
4,datashake,Consultant Paid Media Senior - CDI - Paris,"Tuesday 24 December 2024, 08:37 AM",0.0,75.0,Non spécifié,31 juillet 2024,Télétravail occasionnel,24.0,"En rejoignant datashake, tu bénéficieras d’une...",https://www.welcometothejungle.com/fr/companie...,8,Media
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19358,URGO,Chargé(e) de développement des ressources huma...,"Thursday 12 December 2024, 11:12 AM",0.0,75.0,Non spécifié,05 janvier 2025,Télétravail non autorisé,NaN,Missions :En tant que Chargé(e) de Projet RH a...,https://www.welcometothejungle.com/fr/companie...,8,Ressources_Humaines
19359,bioMérieux,CDD 6 mois Assistant Ressources Humaines Génér...,"Thursday 12 December 2024, 10:20 AM",1.0,69.0,Non spécifié,NaN,Télétravail non autorisé,36.0,Rattaché au Responsable RH du site de Marcy l...,https://www.welcometothejungle.com/fr/companie...,6,Ressources_Humaines
19360,City One,Gestionnaire des Ressources Humaines H/F,"Thursday 12 December 2024, 22:25 PM",0.0,75.0,Non spécifié,NaN,Télétravail non renseigné,NaN,Missions principales du service : Le GEMA (Gro...,https://www.welcometothejungle.com/fr/companie...,NaN,Ressources_Humaines
19361,FutureBrand,CDI - Responsable Ressources Humaines Senior (...,"Thursday 12 December 2024, 15:49 PM",0.0,92.0,Non spécifié,31 janvier 2025,Télétravail fréquent,120.0,Nous recherchons un ou une Responsable Ressour...,https://www.welcometothejungle.com/fr/companie...,NaN,Ressources_Humaines
19362,Hôtel Pullman Paris Centre-Bercy,CDD - CHARGÉ(E) DES RESSOURCES HUMAINES H/F,"Thursday 12 December 2024, 14:52 PM",1.0,75.0,"2,9K à 3,1K € par mois",09 mars 2025,Télétravail occasionnel,NaN,Nous vous proposons le challenge suivant…Dans ...,https://www.welcometothejungle.com/fr/companie...,NaN,Ressources_Humaines

La partie difficile hh le salaire

In [39]:
def fill_salaire(salaire):
    if pd.isna(salaire):  # Gérer les valeurs manquantes
        return None

    salaire = str(salaire).replace(",", ".")  # Remplacer les virgules par des points
    salaire = re.sub(r'(\d+(\.\d+)?\s?mois)', '', salaire, flags=re.IGNORECASE)  # Supprimer '12 mois', '13 mois', etc.

    # Déterminer la catégorie : Horaire, Mensuel, Annuel
    if "horaire" in salaire.lower():
        category = "horaire"
    elif "mensuel" in salaire.lower():
        category = "mensuel"
    elif "annuel" in salaire.lower():
        category = "annuel"
    else:
        category = "unknown"  # Catégorie inconnue, on utilise la devinette

    # Extraire les chiffres du salaire
    numbers = [float(num) for num in re.findall(r'\d+(?:\.\d+)?', salaire)]

    if len(numbers) == 0:  # Aucune valeur numérique trouvée
        return None
    elif len(numbers) >= 3:  # Si trois chiffres trouvés, ne rien faire
        return None
    elif len(numbers) == 2:  # Deux chiffres trouvés, vérifier l'écart
        lower, higher = sorted(numbers)
        if higher / lower > 3:  # Si l'écart dépasse 12 fois, retourner None
            return None
        salary_value = sum(numbers) / 2  # Sinon, prendre la moyenne
    else:  # Un seul chiffre trouvé
        salary_value = numbers[0]

    # Logique de devinette si la catégorie est inconnue
    if category == "unknown":
        if salary_value < 250:  # En dessous de 250, c'est horaire
            category = "horaire"
        elif 250 <= salary_value <= 5000:  # Entre 250 et 5000, c'est mensuel
            category = "mensuel"
        elif salary_value > 5000:  # Au-dessus de 5000, c'est annuel
            category = "annuel"

    # Conversion en salaire annuel
    if category == "horaire":
        return round(salary_value * 35 * 52)  # 35 heures/semaine * 52 semaines
    elif category == "mensuel":
        return round(salary_value * 12)  # 12 mois
    elif category == "annuel":
        return round(salary_value)  # Déjà en annuel
    
    return None

In [41]:
df['salaire_annuel'] = df['salaire_annuel'].apply(fill_salaire)

In [43]:
df['salaire_annuel'].unique()

array([    nan,  96460.,  72800.,  68250.,   9000.,   1820.,   9600.,
        56420.,   4914.,  60606.,  86450.,   7920.,   7200.,   3640.,
        77350.,  59150.,  46410.,  70980.,  10800.,   9100.,   2548.,
        78260., 121030.,  80080., 145600.,  45500.,  63700.,   2730.,
       154700.,  95550.,   5733., 118300.,  54600., 113750.,  61880.,
         8400.,   3822.,   4186.,  55146.,   5187.,   3276.,  50050.,
        47320.,   2002., 100100.,  85540.,  70070.,  74620.,   2184.,
        91000.,   2366.,  73710., 120120., 122850.,  75530.,  83720.,
       104650.,  79170.,      0.,   2275.,   2639.,  81900.,  36400.,
       109200.,  94640.,  50960.,  60060.,  97370.,  95277.,   2912.,
       101920., 125580.,   3003.,   2821.,  69160., 254800.,  42770.,
        10200.,  71890.,  21840.,  93730.,  64610.,  82810.,  65520.,
         4368.,   8040.,  44590.,  57603.,  49686.,  66430.,  58240.,
       136500.,   3185., 177450.,  62790.,  22750.,  84630.,   5460.])

In [47]:
heures_par_semaine = 35
semaines_par_an = 52
heures_annuelles = heures_par_semaine * semaines_par_an
heures_mensuelles = heures_annuelles / 12

def ajuster_salaire(salaire):
    # Correction pour les salaires trop élevés
    if salaire > heures_annuelles * 10000:  # Salaire annuel qui a été mis en horaire
        return salaire / heures_annuelles
    elif heures_annuelles * 1000 < salaire <= heures_annuelles * 10000:  # Salaire mensuel transformé en horaire
        return salaire / heures_mensuelles
    elif 220000 < salaire <= heures_annuelles * 1000:  # Salaire annuel compté comme mensuel
        return salaire / 12
    
    # Correction pour les salaires trop faibles
    elif salaire < 110:  # Salaire horaire transformé en annuel
        return salaire * heures_annuelles
    elif 110 <= salaire <= 1000:  # Salaire horaire transformé en mensuel
        return salaire * heures_mensuelles
    elif 1000 <= salaire <= 3000:  # Salaire mensuel transformé en annuel
        return salaire * 12

    # Pas de transformation nécessaire
    return salaire

df['salaire_annuel'] = df['salaire_annuel'].apply(ajuster_salaire)

In [48]:
import re
import unidecode

def add_salary(description):
    # Si la description est un float ou NaN, la convertir en chaîne vide
    if not isinstance(description, str):
        description = str(description) if pd.notna(description) else ""
    
    # Remplacement des symboles problématiques
    description = description.replace('€', 'EUR')
    description = description.replace(',', '.')
    description = description.replace('¿', ' ')  # Remplace le symbole problématique
    description = description.replace('*', '  ') # Remplace l'astérisque par deux espaces pour faire la coupure
    description = description.replace('/', 'par') # remplacer les "/" par "par "
    # Remplacer les espaces dans les nombres par "rien"
    description = re.sub(r'(?<=\d) (?=\d)', '', description)
    description = re.sub(r'(?<=\d)[\s\u202f\xa0](?=\d)', '', description)
    # Normaliser le texte
    description = unidecode.unidecode(description.lower())
    start_pos = 0  # Position de départ pour la recherche
    salary = None
    category = None
    
    while start_pos < len(description):
        # Identifier le mot 'salaire' ou 'rémunération'
        match = re.search(r'\b(salaire|remuneration)\b', description[start_pos:])
        if not match:
            break  # Pas de mention de salaire/rémunération restante dans le texte
        
        # Position de fin du mot clé trouvé
        match_end = start_pos + match.end()
        
        remaining_text = description[match_end:match_end + 110]  # On cherche plus large pour vérifier
        # Trouver le premier "." non suivi d'un chiffre
        valid_stop_dot = re.search(r'\.(?!\d)', remaining_text)
        # Trouver le premier double espace "  "
        valid_stop_space = re.search(r'  ', remaining_text)

        stop_pos_dot = valid_stop_dot.start() if valid_stop_dot else len(remaining_text)
        stop_pos_space = valid_stop_space.start() if valid_stop_space else len(remaining_text)

        # Prendre le minimum entre 110, le point valide, et le double espace
        stop_pos = min(110, stop_pos_dot, stop_pos_space)
        context = remaining_text[:stop_pos]
                
        # Parcourir les mots du contexte pour détecter le premier montant et la première catégorie
        words = context.split()
        for i in range(len(words) - 1):
            # Vérification des catégories avec deux mots consécutifs
            two_words = f"{words[i]} {words[i+1]}"
            if re.search(r'\b(par[\s]*an|par[\s]*ans|annuel|annuels|annuelle|annuelles)\b', two_words):
                category = "annuel"
            elif re.search(r'\b(mensuel|mensuels|mensuelle|mensuelles|par[\s]*mois)\b', two_words):
                category = "mensuel"
            elif re.search(r'\b(horaire|horaires|par[\s]*heure|par[\s]*heures)\b', two_words):
                category = "horaire"
            
            # Chercher le montant avec EUR ou euro
            if salary is None:
                amount_match = re.match(r'(\d+(?:\.\d+)?)(?:\s*(k|eur|euro|euros|keur|keuros|keuro)\b)', two_words)
                if amount_match:
                    salary = float(amount_match.group(1))
                    if amount_match.group(2) and amount_match.group(2).lower() in ('k', 'keur', 'keuros', 'keuro'):
                        if salary < 500:
                            salary *= 1000 
                            category = "annuel"
                            break
                        else:
                            category = "annuel"
                            break
            
            # Si on a trouvé le montant et la catégorie, on peut arrêter
            if salary is not None and category is not None:
                break
        
        # Si montant et catégorie trouvés, et valeur crédible on arrête. 
        if salary is not None and category is not None:
            if category == 'mensuel' and salary * 12 > 5000:
                break
            if category == 'horaire' and salary * 35 * 52 > 9*35*52:
                break
            if salary > 5000:
                break
        
        # Déplacer la position de départ pour continuer la recherche
        salary = None
        category = None
        start_pos = match_end
    
    if salary is None or category is None:
        return None  # Montant ou catégorie non trouvé
    
    # Convertir le salaire en base annuelle si nécessaire
    if category == "mensuel":
        salary *= 12
    elif category == "horaire":
        salary *= 35 * 52
    
    return round(salary)  # Arrondir le salaire

def add_salary_df(df):
    # Créer un masque pour les lignes où 'salaire_annuel' est NaN
    mask = df["salaire_annuel"].isna()
    
    # Appliquer la fonction add_salary uniquement sur les lignes correspondantes
    df.loc[mask, "salaire_annuel"] = df.loc[mask, "description"].apply(add_salary)
    
    # Retourner le DataFrame mis à jour
    return df

In [49]:
percent_nan_before = df['salaire_annuel'].isna().mean() * 100
df = add_salary_df(df)
percent_nan_after = df['salaire_annuel'].isna().mean() * 100

print(f"Pourcentage de NaN avant : {percent_nan_before:.2f}%")
print(f"Pourcentage de NaN après : {percent_nan_after:.2f}%")

Pourcentage de NaN avant : 83.63%
Pourcentage de NaN après : 83.14%

In [51]:
def add_education(description):
    # Vérifier si la description est une chaîne de caractères
    if not isinstance(description, str):
        return None  # Retourner None si la description n'est pas une chaîne de caractères

    description = unidecode.unidecode(description.lower())
    
    if re.search(r"\baucune\b", description):  
        return 0
    elif re.search(r"\b4eme\b", description):  
        return 1
    elif re.search(r"\b(3[\s]*eme|brevet)\b", description):  
        return 2
    elif re.search(r"\b(cap|bep)\b", description):  
        return 3
    elif re.search(r"\b(bac|baccalaureat)\b(?!\s*\+)", description):  
        return 4
    elif re.search(r"\b(bac[\s]*\+[\s]*2|licence [\s]*2)\b", description):  
        return 5
    elif re.search(r"\b(bac[\s]*\+[\s]*3|licence|licenses)\b", description):  
        return 6
    elif re.search(r"\b(bac[\s]*\+[\s]*4|master[\s]*1)\b", description):  
        return 7
    elif re.search(r"\b(master|master[\s]*2|bac[\s]*\+[\s]*5)\b", description):  
        return 8
    return None

def add_education_df(df):
    mask = df["etude_requise"].isna()
    df.loc[mask, "etude_requise"] = df.loc[mask, "description"].apply(add_education)
    return df

# Pourcentage de NaN avant
percent_nan_before = df['etude_requise'].isna().mean() * 100

# Appliquer la fonction
df = add_education_df(df)

# Pourcentage de NaN après
percent_nan_after = df['etude_requise'].isna().mean() * 100

print(f"Pourcentage de NaN avant : {percent_nan_before:.2f}%")
print(f"Pourcentage de NaN après : {percent_nan_after:.2f}%")

Pourcentage de NaN avant : 51.25%
Pourcentage de NaN après : 41.75%

In [52]:
def add_experience(description):
    # Vérifier si la description est une chaîne de caractères
    if not isinstance(description, str):
        return np.nan

    # Normalisation de la description
    description = unidecode.unidecode(description.lower())

    start_pos = 0  # Position de départ pour la recherche
    experience = None

    while start_pos < len(description):
        # Identifier le mot 'experience'
        match = re.search(r'\bexperience\b', description[start_pos:])
        if not match:
            break  # Pas de mention d'expérience restante dans le texte

        # Position de fin du mot clé trouvé
        match_end = start_pos + match.end()

        # Prendre le contexte autour du mot clé
        context_start = max(0, start_pos + match.start() - 15)  # S'assurer que le début est >= 0
        context_end = match_end + 70
        context = description[context_start:context_end]

        # Vérifier si "premiere experience" est mentionné
        if "premiere experience" in context:
            return 6  # Retourner 6 mois

        # Vérifier la présence d'un nombre suivi de "ans" ou "an"
        match_years = re.search(r'(\d+)\s*(ans|an)', context)
        if match_years:
            return int(match_years.group(1)) * 12  # Convertir en mois

        # Déplacer la position de départ pour continuer la recherche
        start_pos = match_end

    return np.nan  # Retourne None si aucune expérience trouvée

def add_experience_df(df):
    mask = df["experience_requise"].isna()
    df.loc[mask, "experience_requise"] = df.loc[mask, "description"].apply(add_experience)
    return df

# Calcul des pourcentages de NaN
percent_nan_before = df['experience_requise'].isna().mean() * 100

# Appliquer la fonction
df = add_experience_df(df)

percent_nan_after = df['experience_requise'].isna().mean() * 100

print(f"Pourcentage de NaN avant : {percent_nan_before:.2f}%")
print(f"Pourcentage de NaN après : {percent_nan_after:.2f}%")

Pourcentage de NaN avant : 51.33%
Pourcentage de NaN après : 46.29%

In [53]:
df = df[(df['salaire_annuel'].isna()) | (df['salaire_annuel'].between(4000, 300000))]

In [54]:
df.head()

,company,intitule,date,contrat,departement,salaire_annuel,clock,remote,experience_requise,description,lien,etude_requise,source
0,Tenzing Conseil,Manager Transformations durables H/F,"Friday 06 December 2024, 08:15 AM",0.0,75.0,NaN,30 septembre 2024,Télétravail fréquent,84.0,Tenzing accompagne les transitions durables da...,https://www.welcometothejungle.com/fr/companie...,NaN,Media
1,SAPER VEDERE,Social Media Analyst & Conseil en Influence / ...,"Tuesday 29 October 2024, 10:53 AM",11.0,NaN,NaN,05 janvier 2025,Télétravail fréquent,NaN,Qu’offrons-nous?Un stage (de 6 mois ou plus) à...,https://www.welcometothejungle.com/fr/companie...,NaN,Media
2,Eskimoz,Consultant Paid Media H/F - stage,"Tuesday 03 December 2024, 10:49 AM",11.0,92.0,NaN,NaN,Télétravail occasionnel,NaN,Gérer ton propre portefeuille client: start up...,https://www.welcometothejungle.com/fr/companie...,NaN,Media
3,Talan,Manager Média H/F,"Tuesday 24 December 2024, 09:01 AM",0.0,75.0,NaN,NaN,Télétravail fréquent,24.0,Company DescriptionTalan est un groupe interna...,https://www.welcometothejungle.com/fr/companie...,8.0,Media
4,datashake,Consultant Paid Media Senior - CDI - Paris,"Tuesday 24 December 2024, 08:37 AM",0.0,75.0,NaN,31 juillet 2024,Télétravail occasionnel,24.0,"En rejoignant datashake, tu bénéficieras d’une...",https://www.welcometothejungle.com/fr/companie...,8,Media

In [55]:
df.sort_values(by='salaire_annuel', ascending=False)[0:20]

,company,intitule,date,contrat,departement,salaire_annuel,clock,remote,experience_requise,description,lien,etude_requise,source
17048,TAKOMA,Business developer (Chargé de développement co...,"Wednesday 20 November 2024, 23:11 PM",0.0,92.0,177450.0,NaN,Télétravail fréquent,NaN,"Rattaché(e) au Directeur Commercial, vous êtes...",https://www.welcometothejungle.com/fr/companie...,NaN,Vente
16928,TAKOMA,Business developer (Chargé de développement co...,"Wednesday 20 November 2024, 23:11 PM",0.0,92.0,177450.0,NaN,Télétravail fréquent,NaN,"Rattaché(e) au Directeur Commercial, vous êtes...",https://www.welcometothejungle.com/fr/companie...,NaN,Vente
16988,TAKOMA,Business developer (Chargé de développement co...,"Wednesday 20 November 2024, 23:11 PM",0.0,92.0,177450.0,NaN,Télétravail fréquent,NaN,"Rattaché(e) au Directeur Commercial, vous êtes...",https://www.welcometothejungle.com/fr/companie...,NaN,Vente
16898,TAKOMA,Business developer (Chargé de développement co...,"Wednesday 20 November 2024, 23:11 PM",0.0,92.0,177450.0,NaN,Télétravail fréquent,NaN,"Rattaché(e) au Directeur Commercial, vous êtes...",https://www.welcometothejungle.com/fr/companie...,NaN,Vente
16958,TAKOMA,Business developer (Chargé de développement co...,"Wednesday 20 November 2024, 23:11 PM",0.0,92.0,177450.0,NaN,Télétravail fréquent,NaN,"Rattaché(e) au Directeur Commercial, vous êtes...",https://www.welcometothejungle.com/fr/companie...,NaN,Vente
17018,TAKOMA,Business developer (Chargé de développement co...,"Wednesday 20 November 2024, 23:11 PM",0.0,92.0,177450.0,NaN,Télétravail fréquent,NaN,"Rattaché(e) au Directeur Commercial, vous êtes...",https://www.welcometothejungle.com/fr/companie...,NaN,Vente
17108,TAKOMA,Business developer (Chargé de développement co...,"Wednesday 20 November 2024, 23:11 PM",0.0,92.0,177450.0,NaN,Télétravail fréquent,NaN,"Rattaché(e) au Directeur Commercial, vous êtes...",https://www.welcometothejungle.com/fr/companie...,NaN,Vente
17078,TAKOMA,Business developer (Chargé de développement co...,"Wednesday 20 November 2024, 23:11 PM",0.0,92.0,177450.0,NaN,Télétravail fréquent,NaN,"Rattaché(e) au Directeur Commercial, vous êtes...",https://www.welcometothejungle.com/fr/companie...,NaN,Vente
6136,Delpha & Co,Directeur Opérationnel AMO chez Delpha Conseil,"Monday 09 December 2024, 15:02 PM",0.0,78.0,154700.0,NaN,Télétravail fréquent,180.0,Nous recherchons un Directeur Opérationnel AMO...,https://www.welcometothejungle.com/fr/companie...,0,Conseil
14622,Grant Thornton,Senior Manager Audit IT - Public/Banque - Neui...,"Wednesday 11 December 2024, 16:29 PM",0.0,92.0,154700.0,NaN,Télétravail fréquent,84.0,"Notre équipe Audit et Conseil IT, rattachée à ...",https://www.welcometothejungle.com/fr/companie...,8,Audit
5609,Delpha & Co,Directeur Opérationnel AMO chez Delpha Conseil,"Monday 09 December 2024, 15:02 PM",0.0,78.0,154700.0,NaN,Télétravail fréquent,180.0,Nous recherchons un Directeur Opérationnel AMO...,https://www.welcometothejungle.com/fr/companie...,0,Conseil
6167,Delpha & Co,Directeur Opérationnel AMO chez Delpha Conseil,"Monday 09 December 2024, 15:02 PM",0.0,78.0,154700.0,NaN,Télétravail fréquent,180.0,Nous recherchons un Directeur Opérationnel AMO...,https://www.welcometothejungle.com/fr/companie...,0,Conseil
6105,Delpha & Co,Directeur Opérationnel AMO chez Delpha Conseil,"Monday 09 December 2024, 15:02 PM",0.0,78.0,154700.0,NaN,Télétravail fréquent,180.0,Nous recherchons un Directeur Opérationnel AMO...,https://www.welcometothejungle.com/fr/companie...,0,Conseil
14655,Grant Thornton,Senior Manager Audit IT - Public/Banque - Neui...,"Wednesday 11 December 2024, 16:29 PM",0.0,92.0,154700.0,NaN,Télétravail fréquent,84.0,"Notre équipe Audit et Conseil IT, rattachée à ...",https://www.welcometothejungle.com/fr/companie...,8,Audit
15018,Grant Thornton,Senior Manager Audit IT - Public/Banque - Neui...,"Wednesday 11 December 2024, 16:29 PM",0.0,92.0,154700.0,NaN,Télétravail fréquent,84.0,"Notre équipe Audit et Conseil IT, rattachée à ...",https://www.welcometothejungle.com/fr/companie...,8,Audit
5640,Delpha & Co,Directeur Opérationnel AMO chez Delpha Conseil,"Monday 09 December 2024, 15:02 PM",0.0,78.0,154700.0,NaN,Télétravail fréquent,180.0,Nous recherchons un Directeur Opérationnel AMO...,https://www.welcometothejungle.com/fr/companie...,0,Conseil
6074,Delpha & Co,Directeur Opérationnel AMO chez Delpha Conseil,"Monday 09 December 2024, 15:02 PM",0.0,78.0,154700.0,NaN,Télétravail fréquent,180.0,Nous recherchons un Directeur Opérationnel AMO...,https://www.welcometothejungle.com/fr/companie...,0,Conseil
15051,Grant Thornton,Senior Manager Audit IT - Public/Banque - Neui...,"Wednesday 11 December 2024, 16:29 PM",0.0,92.0,154700.0,NaN,Télétravail fréquent,84.0,"Notre équipe Audit et Conseil IT, rattachée à ...",https://www.welcometothejungle.com/fr/companie...,8,Audit
5547,Delpha & Co,Directeur Opérationnel AMO chez Delpha Conseil,"Monday 09 December 2024, 15:02 PM",0.0,78.0,154700.0,NaN,Télétravail fréquent,180.0,Nous recherchons un Directeur Opérationnel AMO...,https://www.welcometothejungle.com/fr/companie...,0,Conseil
5578,Delpha & Co,Directeur Opérationnel AMO chez Delpha Conseil,"Monday 09 December 2024, 15:02 PM",0.0,78.0,154700.0,NaN,Télétravail fréquent,180.0,Nous recherchons un Directeur Opérationnel AMO...,https://www.welcometothejungle.com/fr/companie...,0,Conseil